name: zfish-cilia-csf-env
channels:
  - conda-forge
dependencies:
  - python
  - fenics-dolfinx
  - adios4dolfinx
  - numpy
  - matplotlib
  - pyvista 
  - scipy
  - pandas
  - git
  - vtk
  - mpich
  - tabulate
  - meshio
  - colormaps
  - conda-ecosystem-user-package-isolation